안드로이드 25조 5주차 개발 완료(매니저 앱)
kakao-tech-campus-2nd-step3/Team25_Android_2 pull request #20
Opened 2024-10-04 12:39 UTC by ichanguk

금주 개발 사항

- 실시간 동행 현황 화면 기능 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android_2/pull/13)
- 근무 시간 지정 기능 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android_2/pull/14)
- 위치 정보 기능 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android_2/pull/15)
- 로그인 기능 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android_2/pull/16)
- 매니저 프로필 이미지 업로드 기능 추가(https://github.com/kakao-tech-campus-2nd-step3/Team25_Android_2/pull/17)

차주 개발 예정 사항
- 서버와 api 연동(로그인, 매니저 등록, 매니저 검색, 예약, 결제)

2024-10-06 15:20 UTC, bigstark requested changes
이번 주차도 고생 많으셨어요! 깔끔하네요!

https://github.com/kakao-tech-campus-2nd-step3/Team25_Android/pull/46 와 겹치는 것이 많아, 겹치는 것은 리뷰를 생략했습니다 :)

2024-10-06 15:20 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    @Provides
p2; retrofit 은 singleton 으로 제공되어야할 것 같네요!

2024-10-06 15:20 UTC, bigstark commented on app/src/main/java/com/example/team25/domain/model/PaymentInfo.kt
> +    val paymentDate: Date = Date(),
p4; Date 사용시 ZonedDateTime 이나 LocalDateTime 사용을 추천드립니다 :)

2024-10-06 15:20 UTC, bigstark commented on app/src/main/java/com/example/team25/dto/DaySchedule.kt
> +    var end_time: String = "00:00"
p5; 이부분 컨벤션이 맞지 않는 것 같아요!

2024-10-06 15:20 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/companion/LiveCompanionActivity.kt
> +            repeatOnLifecycle(Lifecycle.State.STARTED){
GOOD 👍

2024-10-06 15:20 UTC, bigstark commented on app/src/main/java/com/example/team25/ui/status/CompanionCompleteDialog.kt
> +    Dialog(context) {
p4; Dialog 보다는 DialogFragment 사용하심이 어떨까요?!

2024-10-08 04:40 UTC, bigstark commented on app/src/main/java/com/example/team25/di/NetworkModule.kt
> +    @Provides
요기도 이부분만 수정해주시면 머지해보록 해볼게요

2024-10-08 09:46 UTC, ichanguk commented
이용자앱에 반영된 리뷰 내용 적용 pr 올렸습니다. merge 해주시면 감사하겠습니다!

2024-10-12 18:43 UTC, bigstark approved these changes
요건 approve 해둘게요 머지해주세요!

2024-10-12 20:20 UTC, merged